export type IMPORT_PURPOSE = "IMPORT_SESSIONS" | "IMPORT_PRESENTATIONS";
export type EXPORT_PURPOSE = "EXPORT_SESSIONS" | "EXPORT_PRESENTATIONS";

export type PURPOSE = IMPORT_PURPOSE | EXPORT_PURPOSE;
